service: pdf-generator

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  profile: default
  timeout: 30
  memorySize: 512
  stage: development
  environment:
    NODE_ENV: development

functions:
  generatePdf:
    handler: src/pdf.pdf
    events:
      - http:
          path: v1/generate-pdf
          method: post
          cors: true

plugins:
  - serverless-offline
  - serverless-apigw-binary

custom:
  apigwBinary:
    types:
      - "*/*"
